# Generated by Django 2.2.2 on 2020-07-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='image',
            field=models.FileField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to='media/videos/'),
        ),
    ]
