# Generated by Django 2.2.2 on 2020-07-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_auto_20200718_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
