# Generated by Django 2.2.2 on 2020-07-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0003_auto_20200718_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jayanth',
            fields=[
                ('email', models.CharField(default=None, max_length=50, primary_key=True, serialize=False, verbose_name='Email')),
                ('password', models.CharField(default=None, max_length=50, verbose_name='Password')),
            ],
        ),
    ]
